### ISSUE TITLE
Instructions Incorrect

### ISSUE THREAD

**Issue by belcherj** [googlecodelabs/polymer-first-elements#12] opened 2015-11-12 00:33 UTC
On: 

http://www.code-labs.io/codelabs/polymer-first-elements/index.html?index=..%2F..%2Fpolymer-summit&viewga=UA-39334307-12#4

It says:

If you run the demo now, you won't see any icon at all; there's no default value for the toggleIcon property. You can set it programmatically, like this

This is incorrect.  It will show the icons that are passed in via the demo code: 
`<icon-toggle toggle-icon="star"></icon-toggle>`

**Comment by arthurevans** [comment] 2015-11-12 03:25
Thanks. This is a duplicate of #5. Fixing this now, hope to have an updated version of the codelab out this week.

The current version of this repo is also slightly out of sync with the codelab, which will be fixed when we update. (I note this in case you're running through it right now--icon-toggle.html, the demo folder, etc., are now at the top level so you can just git clone the project directly into CDE.

**Comment by belcherj** [comment] 2015-11-12 03:38
Thanks, Sorry to have duped.  Thought I read through them all.  Feel free to close.

**Comment by arthurevans** [comment] 2015-11-17 16:08
Codelab is updated and hopefully clearer now. Thanks for the report!

**Closed as completed by arthurevans** 2015-11-17 16:08 UTC
